### ISSUE TITLE
Changing parameter

### ISSUE THREAD

**Issue by SomeoneGrouf** [Khainaaeh/44CALIBER#5]
Wich parameter need to be changed

**Comment by razexgod** [comment]
1,2,3
u need to change value in ""
first - ur discord webhook
second - ur bot name (only english)
third - same as second

**Comment by SomeoneGrouf** [comment]
i did that 

    private static string defaultWebhook = "https://discord.com/api/webhooks/807252214996795442/aLSsIdGb1nNhEJzkaMlnDwhmaiobi893kpyGnFPOW94aTB2SQTdDXHl2uotpr7w7fUR5";
    private static string defaultUserAgent = "test";
    private static string defaultUserName = "test";
    private static string defaultAvatar = ""; // можно не заполнять, бесполезная хрень

but not working

**Comment by razexgod** [comment]
did u test it on vm or dedicated server?

**Comment by SomeoneGrouf** [comment]
> did u test it on vm or dedicated server?

Yes

**Comment by razexgod** [comment]
> > did u test it on vm or dedicated server?
> 
> Yes

Stealer doesnt work on vm/dedic or something else.
u can test it in your own PC

**Comment by SomeoneGrouf** [comment]
I did , still don't work

**Comment by razexgod** [comment]
> I did , still don't work

do u have winrar? try to recreate webhook api, if it wont working again, pm me telegram chaosinsurgency

**Comment by hekcemrnrna** [comment]
hi Khainaaeh your Telegram does not work anymore can you give me your new ? My problem is that on some pcs like on my laptop the virus works but nothing else please help if everything works i will donate
