### ISSUE TITLE
нужна помощь

### ISSUE THREAD

**Issue by 13MrBlackCat13** [Khainaaeh/44CALIBER#7]
а как добавить иконку?
просто я не нашел файл csproj

**Comment by 13MrBlackCat13** [comment]
а теперь код не компилируеться

**Comment by 13MrBlackCat13** [comment]
https://i.imgur.com/eq13EBI.png

**Comment by razexgod** [comment]
Это уже ты что-то понаделал. Ничем не могу помочь.
