### ISSUE TITLE
Где взять бусты для дискорд сервера?

### ISSUE THREAD

**Issue by nflsx1993** [Khainaaeh/44CALIBER#8]
![Screenshot_154](https://user-images.githubusercontent.com/82864483/115649532-2d60ac00-a330-11eb-9f1d-8e08eb9b742d.png)

стилер неплохой, но вот где взять бусты для сервера? можешь посоветовать?

**Comment by razexgod** [comment]
это покупать в самом дискорде улучшение для сервера

**Comment by nflsx1993** [comment]
если в телеге сидишь, напиши плиз @godblessyouorme
